services:

  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./config.json:/etc/selenoid/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/config.json", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8081:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  resipetest:
    build: .
    container_name: resipetest
    volumes:
      - ".:/app"
    depends_on:
      - selenoid
    networks:
      - selenoid
    command: ["pytest"]

networks:
  selenoid:
    name: selenoid